Source Files for PP
bountonw/translate pull request #52
Opened 2024-01-30 08:02 UTC by tonyquicktech

Sources file for PP are ready to be merged.

2024-01-30 12:52 UTC, bountonw commented
I just noticed that the MB files are in this same branch. Can you move them to a different branch and create a separate pull request?

2024-01-30 13:22 UTC, mattleff commented
> @mattleff Can you check if the fails are do to a problem with our linting or with the files.

@bountonw I've pushed #53 to fix some incorrect fails. The rest are legitimate.

2024-01-30 13:40 UTC, bountonw commented
@tonyquicktech @mattleff MB should be on a separate PR

2024-01-30 13:42 UTC, bountonw requested changes
MB is a separate issue and should be separate PR.

2024-01-30 13:44 UTC, tonyquicktech commented
Noted - I made the pull request before making the MB files, so, I'll make a new branch and add a new PR

2024-01-31 14:07 UTC, bountonw requested changes
Please remove the MB files from the PP pull request.

2024-01-31 14:13 UTC, tonyquicktech commented
> MB is a separate issue and should be separate PR.

Done

2024-01-31 14:22 UTC, bountonw requested changes
Rename the preface and introduction so that `_en` is the last thing in the filename before the file extension.

2024-01-31 14:25 UTC, bountonw commented on source/PP/PP74_en_appendix.md
Please split the Appendix entrees into separate files as per the `th/PP/` files. They are in the form of `PP21_AN1_th.md`. (This is an example. I don't remember what chapter Appendix Note 1 is in.)

2024-02-01 02:49 UTC, bountonw approved these changes

2024-02-01 02:52 UTC, merged