MB Source Files (formatted)
bountonw/translate pull request #54
Opened 2024-01-30 13:47 UTC by tonyquicktech

2024-01-30 13:49 UTC, tonyquicktech commented
Hmm, it looks like it wants to merge everything from the source folder :3

2024-01-31 14:06 UTC, bountonw requested changes
Please remove the PP files from the MB pull request.

2024-01-31 14:12 UTC, tonyquicktech commented
> Please remove the PP files from the MB pull request.

Done

2024-01-31 14:19 UTC, bountonw commented on source/MB/MB00a_en_forward.md
File name should be `MB00a_forward_en.md`. The language suffix, in this case `_en`, should be the last thing before the file extension.

2024-01-31 14:20 UTC, bountonw requested changes
Rename forward and preface so that the `_en` file extension is the last thing in the file name.

2024-01-31 14:24 UTC, tonyquicktech commented on source/MB/MB00b_en_preface.md
Done

2024-01-31 14:24 UTC, tonyquicktech commented on source/MB/MB00a_en_forward.md
Done

2024-01-31 14:33 UTC, bountonw approved these changes

2024-01-31 14:34 UTC, merged